version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: url-shortener-db
    restart: always
    environment:
      POSTGRES_USER: shortener_user
      POSTGRES_PASSWORD: shortener_pass
      POSTGRES_DB: url_shortener
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - shortener_network

  url-shortener:
    build: .
    container_name: url-shortener
    restart: always
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: shortener_user
      DB_PASS: shortener_pass
      DB_NAME: url_shortener
      DATABASE_URL: "postgresql://shortener_user:shortener_pass@postgres:5432/url_shortener"
    ports:
      - "3000:3000"
    networks:
      - shortener_network
    command: ["npm", "run", "start"]

networks:
  shortener_network:
    driver: bridge

volumes:
  pgdata:
    driver: local
