version: "3.8"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: urlshortener
    ports:
      - "5432:5432"
  api:
    build: ./api
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://user:password@db:5432/urlshortener"
  web:
    build: ./web
    ports:
      - "3000:3000"
    depends_on:
      - api

