services:
  postgres:
    image: postgres:15
    container_name: url-shortener-db
    restart: always
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - shortener_network

  url-shortener:
    build: .
    container_name: url-shortener
    restart: always
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: testuser
      DB_PASS: testpass
      DB_NAME: testdb
      MIGRATIONS_PATH: /app/apps/api/dist/migrations/*.js
    ports:
      - "3000:3000"
    networks:
      - shortener_network
    command: [ "sh", "-c", "sleep 5 && npm run start" ]
networks:
  shortener_network:
    driver: bridge

volumes:
  pgdata:
    driver: local
